package jetbrains.mps.tutorial.calculator.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import javax.swing.JTextField;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

public class MyCalc extends JFrame {
  private DocumentListener listener = new DocumentListener() {
    public void insertUpdate(DocumentEvent p0) {
      update();
    }

    public void removeUpdate(DocumentEvent p0) {
      update();
    }

    public void changedUpdate(DocumentEvent p0) {
      update();
    }
  };

  private JTextField input_a = new JTextField();
  private JTextField input_b = new JTextField();
  private JTextField input_c = new JTextField();
  private JTextField output_a = new JTextField();



  public MyCalc() {
    setTitle("MyCalc");
    setLayout(new GridLayout(0, 2));
    input_a.getDocument().addDocumentListener(listener);
    add(new JLabel("width"));
    add(input_a);
    input_b.getDocument().addDocumentListener(listener);
    add(new JLabel("height"));
    add(input_b);
    input_c.getDocument().addDocumentListener(listener);
    add(new JLabel("depth"));
    add(input_c);
    add(new JLabel("Output"));
    add(output_a);
    update();
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    pack();
    setVisible(true);
  }

  public void update() {
    int i_a = 0;
    int i_b = 0;
    int i_c = 0;
    try {
      i_a = Integer.parseInt(input_a.getText());
      i_b = Integer.parseInt(input_b.getText());
      i_c = Integer.parseInt(input_c.getText());
    } catch (NumberFormatException e) {
    }
    output_a.setText("" + (2 + 2));
  }

  public static void main(String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        new MyCalc();
      }
    });
  }
}
