package jetbrains.mps.tutorial.calculator.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 0:
        return new Calculator_BehaviorDescriptor();
      case 1:
        return new InputField_BehaviorDescriptor();
      case 3:
        return new OutputField_BehaviorDescriptor();
      case 2:
        return new InputFieldReference_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"jetbrains.mps.tutorial.calculator.structure.Calculator", "jetbrains.mps.tutorial.calculator.structure.InputField", "jetbrains.mps.tutorial.calculator.structure.InputFieldReference", "jetbrains.mps.tutorial.calculator.structure.OutputField"};
}
