package jetbrains.mps.tutorial.calculator.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class InputFieldReference_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public InputFieldReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.tutorial.calculator.structure.InputFieldReference";
  }
}
