package jetbrains.mps.tutorial.calculator.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class OutputField_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public OutputField_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.tutorial.calculator.structure.OutputField";
  }
}
