package pl0.behavior;

/*Generated by MPS */


public class AssignStmt_BehaviorDescriptor extends Stmt_BehaviorDescriptor {
  public AssignStmt_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "pl0.structure.AssignStmt";
  }
}
