package pl0.behavior;

/*Generated by MPS */


public class BeginStmt_BehaviorDescriptor extends Stmt_BehaviorDescriptor {
  public BeginStmt_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "pl0.structure.BeginStmt";
  }
}
