package pl0.behavior;

/*Generated by MPS */


public class DyadicExpr_BehaviorDescriptor extends Expr_BehaviorDescriptor {
  public DyadicExpr_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "pl0.structure.DyadicExpr";
  }
}
