package pl0.behavior;

/*Generated by MPS */


public class IntLiteral_BehaviorDescriptor extends Expr_BehaviorDescriptor {
  public IntLiteral_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "pl0.structure.IntLiteral";
  }
}
