package pl0.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class IntLiteral_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public IntLiteral_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "pl0.structure.IntLiteral";
  }
}
