package pl0.behavior;

/*Generated by MPS */


public class Odd_BehaviorDescriptor extends Expr_BehaviorDescriptor {
  public Odd_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "pl0.structure.Odd";
  }
}
