package pl0.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Odd_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Odd_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "pl0.structure.Odd";
  }
}
