package pl0.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Stmt_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Stmt_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "pl0.structure.Stmt";
  }
}
