package pl0.behavior;

/*Generated by MPS */


public abstract class TBoolean_BehaviorDescriptor extends TValue_BehaviorDescriptor {
  public TBoolean_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "pl0.structure.TBoolean";
  }
}
