package pl0.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class TInteger_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TInteger_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "pl0.structure.TInteger";
  }
}
