package pl0.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class TValue_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TValue_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "pl0.structure.TValue";
  }
}
