package pl0.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class VarDefs_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public VarDefs_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "pl0.structure.VarDefs";
  }
}
