package pl0.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class VarDef_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public VarDef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "pl0.structure.VarDef";
  }
}
