package pl0.behavior;

/*Generated by MPS */


public class VarRef_BehaviorDescriptor extends Expr_BehaviorDescriptor {
  public VarRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "pl0.structure.VarRef";
  }
}
